export const ServicesDatas = [
    {id : 1 , Title : "Social Media" , icons : "fa-solid fa-hashtag" , ServicesDesc : "is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer"},
    {id : 2 , Title : "Digital Services" , icons : "fas fa-digital-tachograph" , ServicesDesc : "is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer"},
    {id : 3 , Title : "News and Media" , icons : "fas fa-newspaper" , ServicesDesc : "is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer"},
    {id : 4 , Title : "Mail Services" , icons : "fa-solid fa-envelope" , ServicesDesc : "is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer"},
    {id : 5 , Title : "Brand management" , icons : "fa-solid fa-chart-simple" , ServicesDesc : "is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer"},
    {id : 6 , Title : "Crypto Currency" , icons : "fa-brands fa-btc" , ServicesDesc : "is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer"},
    {id : 7 , Title : "financial system" , icons : "fa-brands fa-btc" , ServicesDesc : "is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer"},
    {id : 8 , Title : "central bank" , icons : "fa-brands fa-btc" , ServicesDesc : "is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer"},
    {id : 9 , Title : "bitcoin mine" , icons : "fa-brands fa-btc" , ServicesDesc : "is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer"},
    {id : 10 , Title : "etherium Market" , icons : "fa-brands fa-btc" , ServicesDesc : "is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer"},
]